name: magicstep
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  cookie_jar: ^3.0.1
  dio: ^4.0.6
  dio_cookie_manager: ^2.0.0
  flutter:
    sdk: flutter
  flutter_barcode_scanner: ^2.0.0
  flutter_bloc: ^8.0.1
  flutter_html_to_pdf: ^0.7.0
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^5.0.2
  intl: ^0.17.0
  path_provider: ^2.0.9
  pdf: ^3.7.4
  permission_handler: ^9.2.0
  uc_pdfview: ^0.0.3
  url_launcher: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/CustomIcons.ttf
